system:
  debug: 
    mode: True
    log_level: debug

github:
  owner: "pacificbelt30"
  repo: "alert-menta"

ai:
  model: "gpt-3.5-turbo" # Check the list of available models by `curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"`
  
  commands:
    - describe:
        description: "Describe the GitHub Issues"
        system_prompt: "The following is the GitHub Issue and comments on it. Please summarize the conversation and suggest what issues need to be resolved.\n"
    - improve:
        description: "Improve the GitHub Issues"
        system_prompt: "The following is the GitHub Issue and comments on it. Please identify the issues that need to be resolved based on the contents of the Issue and provide three suggestions for improvement."